- name: Azure Pipelines Action
  uses: Azure/pipelines@v1

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        
